name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: linux
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 17.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable caching for npm dependencies

      - name: Install dependencies
        run: npm install

      - name: Log installed packages
        run: npm list

      - name: Build production project
        run: npm run build:prod

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint CSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run screenshot tests
        run: npm run test:ui:ci
